"""Generate a Lean `SphericalMap` for an oriented triangulation given by its faces, following the
library's `Icosahedron.lean`: next/prev tables, face labels, and a linear `Fills` certificate
(dual spanning tree potentials + enclosed-vertex incidence coefficients).
Usage: python3 -I gen_smap.py <faces.json (list of [a,b,c] or {"faces": ...})> <Namespace> <doc line>"""
import json, sys
from collections import deque
J = json.load(open(sys.argv[1])); faces = J['faces'] if isinstance(J, dict) else J
NS, DOC = sys.argv[2], sys.argv[3]
N = 1 + max(max(f) for f in faces); F = len(faces)
darts = {}
for i, (a, b, c) in enumerate(faces):
    for u, v in ((a, b), (b, c), (c, a)):
        assert (u, v) not in darts, ('inconsistent orientation', u, v); darts[(u, v)] = i
assert all((v, u) in darts for (u, v) in darts)
nxt = {}
for (a, b, c) in faces:
    nxt[(b, a)] = c; nxt[(c, b)] = a; nxt[(a, c)] = b
prv = {(u, w): v for (u, v), w in nxt.items()}
edges = sorted({(min(u, v), max(u, v)) for (u, v) in darts}); E = len(edges)
assert N - E + F == 2
eidx = {}
for i, (u, v) in enumerate(edges): eidx[(u, v)] = eidx[(v, u)] = i
deg = [sum(1 for (u, v) in darts if u == x) for x in range(N)]; D = max(deg)
# rotation orbits are single cycles
for x in range(N):
    nb = [v for (u, v) in darts if u == x]; cur = nb[0]; seen = []
    for _ in range(len(nb)): seen.append(cur); cur = nxt[(x, cur)]
    assert sorted(seen) == sorted(nb) and cur == nb[0]
# dual tree potentials
par = {0: None}; q = deque([0])
fe = {}  # face -> list of (edge, other face)
for (u, v), f in darts.items(): fe.setdefault(f, []).append((eidx[(u, v)], darts[(v, u)]))
while q:
    f = q.popleft()
    for e, g in fe[f]:
        if g not in par: par[g] = (f, e); q.append(g)
assert len(par) == F
pc = [[0]*E for _ in range(F)]
for f in range(F):
    g = f
    while par[g] is not None: pc[f][par[g][1]] ^= 1; g = par[g][0]
adjl = [[] for _ in range(N)]
for (u, v) in edges: adjl[u].append(v); adjl[v].append(u)
inc = [[0]*N for _ in range(E)]
for i, (u, v) in enumerate(edges):
    f, g = darts[(u, v)], darts[(v, u)]
    C = {e for e in range(E) if (pc[f][e] ^ pc[g][e] ^ (e == i))}
    if not C: continue
    X = {u}; q = [u]
    while q:
        a = q.pop()
        for b in adjl[a]:
            if eidx[(a, b)] not in C and b not in X: X.add(b); q.append(b)
    assert {e for e, (a, b) in enumerate(edges) if (a in X) != (b in X)} == C
    for x in X: inc[i][x] = 1
# check certificate in Python
for (u, v) in darts:
    i = eidx[(u, v)]
    for e, (a, b) in enumerate(edges):
        lhs = (i == e) ^ (sum(inc[i][x] for x in (a, b)) % 2)
        assert lhs == pc[darts[(u, v)]][e] ^ pc[darts[(v, u)]][e]
def tab(f, rows, cols):
    return '![' + ', '.join('![' + ', '.join(str(f(r, c)) for c in range(cols)) + ']' for r in range(rows)) + ']'
reps = [(a, b) for (a, b, c) in faces]
repl = '![' + ', '.join(f'({a}, {b})' for a, b in reps) + ']'
print(f'''module
public import Mathlib.Combinatorics.SimpleGraph.PlaneMap.SphericalCompletion
public import Mathlib.Dynamics.PeriodicPts.Lemmas
public import Mathlib.Tactic
/-!
# {DOC}

Generated by `gen_smap.py` from an oriented face list, following the library's
`Icosahedron.lean`: {N} vertices, {E} edges, {F} triangular faces. The tables are input data;
invalid tables fail one of the finite kernel checks. `Fills` is proved by the linear
certificate: dual-spanning-tree potentials and enclosed-vertex incidence coefficients.
-/

@[expose] public section
namespace SimpleGraph.{NS}
open scoped BigOperators
set_option maxRecDepth 8192
set_option maxHeartbeats 0

def endpoints : Fin {E} → Fin {N} × Fin {N} := ![{', '.join(f'({u}, {v})' for u, v in edges)}]
def graph : SimpleGraph (Fin {N}) where
  Adj u v := ∃ e : Fin {E}, endpoints e = (u,v) ∨ endpoints e = (v,u)
  symm := by refine ⟨?_⟩; intro u v h; obtain ⟨e,h⟩ := h; exact ⟨e,h.symm⟩
  loopless := by
    refine ⟨?_⟩
    intro v h
    obtain ⟨e,h⟩ := h
    have hn : ∀ e : Fin {E}, (endpoints e).1 ≠ (endpoints e).2 := by decide
    apply hn e
    rcases h with h | h <;> simp [h]

def adjB : Fin {N} → Fin {N} → Bool := {tab(lambda u, v: 'true' if (u, v) in darts else 'false', N, N)}
theorem adj_iff : ∀ u v : Fin {N}, (∃ e : Fin {E}, endpoints e = (u,v) ∨ endpoints e = (v,u)) ↔
    adjB u v = true := by decide
instance : DecidableRel graph.Adj := fun u v => decidable_of_iff (adjB u v = true) (adj_iff u v).symm
def nextTable : Fin {N} → Fin {N} → Fin {N} := {tab(lambda u, v: nxt.get((u, v), 0), N, N)}
def prevTable : Fin {N} → Fin {N} → Fin {N} := {tab(lambda u, v: prv.get((u, v), 0), N, N)}
def labelTable : Fin {N} → Fin {N} → Fin {F} := {tab(lambda u, v: darts.get((u, v), 0), N, N)}
def edgeTable : Fin {N} → Fin {N} → Fin {E} := {tab(lambda u, v: eidx.get((u, v), 0), N, N)}
def degTable : Fin {N} → ℕ := ![{', '.join(map(str, deg))}]
theorem next_adj : ∀ u v, graph.Adj u v → graph.Adj u (nextTable u v) := by decide
theorem prev_adj : ∀ u v, graph.Adj u v → graph.Adj u (prevTable u v) := by decide
def nextDart (d : graph.Dart) : graph.Dart := ⟨(d.fst, nextTable d.fst d.snd), next_adj _ _ d.adj⟩
def prevDart (d : graph.Dart) : graph.Dart := ⟨(d.fst, prevTable d.fst d.snd), prev_adj _ _ d.adj⟩
def rotation : RotationSystem graph where
  next := {{
    toFun := nextDart
    invFun := prevDart
    left_inv := by
      have h : ∀ u v, graph.Adj u v → prevTable u (nextTable u v) = v := by decide
      intro d; apply Dart.ext; exact Prod.ext rfl (h _ _ d.adj)
    right_inv := by
      have h : ∀ u v, graph.Adj u v → nextTable u (prevTable u v) = v := by decide
      intro d; apply Dart.ext; exact Prod.ext rfl (h _ _ d.adj) }}
  next_fst := fun _ => rfl
  cyclic := by
    have h : ∀ u v w, graph.Adj u v → graph.Adj u w →
      ∃ k : Fin {D}, (nextTable u)^[k.val] v = w := by decide
    intro d e he
    obtain ⟨k,hk⟩ := h d.fst d.snd e.snd d.adj (by simp [he])
    refine ⟨k.val, ?_⟩
    apply Dart.ext
    have hi : ∀ k : ℕ, ((nextDart : graph.Dart → graph.Dart)^[k] d).toProd =
      (d.fst, (nextTable d.fst)^[k] d.snd) := by
      intro k; induction k with
      | zero => rfl
      | succ k ih =>
        rw [Function.iterate_succ_apply']; change (_, nextTable _ _) = _
        rw [ih]; simp only [Function.iterate_succ_apply']
    change ((nextDart : graph.Dart → graph.Dart)^[k.val] d).toProd = e.toProd
    rw [hi]; exact Prod.ext he hk
def representatives : Fin {F} → graph.Dart := fun f => ⟨{repl} f, by
  have h : ∀ f : Fin {F}, graph.Adj (({repl} : Fin {F} → Fin {N} × Fin {N}) f).1
      (({repl} : Fin {F} → Fin {N} × Fin {N}) f).2 := by decide
  exact h f⟩
/-- Linear face-potential reconstruction, rooted at face zero. -/
def potentialCoeffs : Fin {F} → Fin {E} → ZMod 2 := {tab(lambda f, e: pc[f][e], F, E)}
/-- Vertex-incidence coefficients for each edge's dual-cycle discrepancy. -/
def incidenceCoeffs : Fin {E} → Fin {N} → ZMod 2 := {tab(lambda e, x: inc[e][x], E, N)}

theorem label_next (d : graph.Dart) :
    labelTable (rotation.faceNext d).fst (rotation.faceNext d).snd =
      labelTable d.fst d.snd := by
  have h : ∀ u v, graph.Adj u v → labelTable v (nextTable v u) = labelTable u v := by decide
  exact h _ _ d.adj

def faceIndex : rotation.Face → Fin {F}
  | .inl q => Quotient.lift (fun d : graph.Dart => labelTable d.fst d.snd) (by
      intro d e h
      induction h with
      | refl d => rfl
      | step d => exact (label_next d).symm
      | symm h ih => exact ih.symm
      | trans h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂) q
  | .inr h => False.elim (@IsEmpty.false graph.Dart h.property (representatives 0))

@[simp] theorem faceIndex_faceOf (d : graph.Dart) :
    faceIndex (rotation.faceOf d) = labelTable d.fst d.snd := rfl

def indexedEdge (e : Fin {E}) : graph.edgeSet :=
  ⟨s((endpoints e).1, (endpoints e).2), by
    rw [mem_edgeSet]
    exact ⟨e, Or.inl (Prod.eta _)⟩⟩

theorem indexedEdge_dart (d : graph.Dart) :
    indexedEdge (edgeTable d.fst d.snd) = RotationSystem.edgeOfDart d := by
  have h : ∀ u v, graph.Adj u v →
      s((endpoints (edgeTable u v)).1, (endpoints (edgeTable u v)).2) = s(u,v) := by decide
  apply Subtype.ext
  exact h _ _ d.adj

theorem indexedEdge_injective : Function.Injective indexedEdge := by
  have h : ∀ i j : Fin {E},
    s((endpoints i).1, (endpoints i).2) = s((endpoints j).1, (endpoints j).2) → i = j := by decide
  intro i j hij
  exact h i j (congrArg Subtype.val hij)

theorem indexedEdge_surjective : Function.Surjective indexedEdge := by
  intro e
  obtain ⟨d, hd⟩ := RotationSystem.edge_of_dart_surjective e
  exact ⟨edgeTable d.fst d.snd, (indexedEdge_dart d).trans hd⟩

noncomputable def edgeEquiv : Fin {E} ≃ graph.edgeSet :=
  Equiv.ofBijective indexedEdge ⟨indexedEdge_injective, indexedEdge_surjective⟩

theorem degree_eq (v : Fin {N}) : graph.degree v = degTable v := by
  have h : ∀ v : Fin {N}, graph.degree v = degTable v := by decide
  exact h v

def faceRepresentative (f : Fin {F}) : rotation.Face := rotation.faceOf (representatives f)

@[simp] theorem faceIndex_representative (f : Fin {F}) :
    faceIndex (faceRepresentative f) = f := by
  have h : ∀ f : Fin {F}, labelTable (representatives f).fst (representatives f).snd = f := by decide
  exact h f

theorem representative_faceOf (d : graph.Dart) :
    faceRepresentative (labelTable d.fst d.snd) = rotation.faceOf d := by
  have h : ∀ u v, graph.Adj u v →
    ∃ k : Fin 3, ((fun p : Fin {N} × Fin {N} => (p.2, nextTable p.2 p.1))^[k.val])
      (representatives (labelTable u v)).toProd = (u,v) := by decide
  obtain ⟨k,hk⟩ := h d.fst d.snd d.adj
  have hi : ∀ j : ℕ, (rotation.faceNext^[j] (representatives (labelTable d.fst d.snd))).toProd =
    ((fun p : Fin {N} × Fin {N} => (p.2, nextTable p.2 p.1))^[j])
      (representatives (labelTable d.fst d.snd)).toProd := by
    intro j
    induction j with
    | zero => rfl
    | succ j ih =>
      simp only [Function.iterate_succ_apply']
      change (_, nextTable _ _) = _
      change (((rotation.faceNext^[j] (representatives (labelTable d.fst d.snd))).toProd).2,
        nextTable (((rotation.faceNext^[j] (representatives (labelTable d.fst d.snd))).toProd).2)
          (((rotation.faceNext^[j] (representatives (labelTable d.fst d.snd))).toProd).1)) = _
      rw [ih]
  have he : rotation.faceNext^[k.val] (representatives (labelTable d.fst d.snd)) = d := by
    apply Dart.ext
    rw [hi, hk]
  apply congrArg Sum.inl
  apply Quotient.sound
  change rotation.FaceRelation (representatives (labelTable d.fst d.snd)) d
  have hr : ∀ j : ℕ, rotation.FaceRelation (representatives (labelTable d.fst d.snd))
      (rotation.faceNext^[j] (representatives (labelTable d.fst d.snd))) := by
      intro j
      induction j with
      | zero => exact .refl _
      | succ j ih => rw [Function.iterate_succ_apply']; exact ih.trans (.step _)
  simpa [he] using hr k.val

noncomputable def faceEquiv : rotation.Face ≃ Fin {F} where
  toFun := faceIndex
  invFun := faceRepresentative
  left_inv := by
    intro f
    cases f with
    | inl q =>
      induction q using Quotient.inductionOn with
      | h d => exact representative_faceOf d
    | inr h => exact False.elim (@IsEmpty.false graph.Dart h.property (representatives 0))
  right_inv := faceIndex_representative

def incidenceEntry (e : Fin {E}) (v : Fin {N}) : ZMod 2 :=
  if v = (endpoints e).1 ∨ v = (endpoints e).2 then 1 else 0

theorem incidence_coordinates (φ : graph.edgeSet → ZMod 2) (v : Fin {N}) :
    edgeIncidence graph φ v = ∑ e : Fin {E}, incidenceEntry e v * φ (indexedEdge e) := by
  classical
  let : DecidableRel graph.Adj := Classical.decRel _
  unfold edgeIncidence
  calc
    (∑ e : graph.edgeSet, if v ∈ e.val then φ e else 0) =
        ∑ e : Fin {E}, if v ∈ (edgeEquiv e).val then φ (edgeEquiv e) else 0 :=
      (edgeEquiv.sum_comp (fun e : graph.edgeSet => if v ∈ e.val then φ e else 0)).symm
    _ = _ := by
      congr 1
      funext e
      change (if v ∈ (indexedEdge e).val then φ (indexedEdge e) else 0) = _
      simp only [incidenceEntry, indexedEdge, Sym2.mem_iff, ite_mul, one_mul, zero_mul]

def potential (φ : graph.edgeSet → ZMod 2) (f : Fin {F}) : ZMod 2 :=
  ∑ e : Fin {E}, potentialCoeffs f e * φ (indexedEdge e)

set_option maxHeartbeats 0 in
theorem coefficient_certificate : ∀ u v, graph.Adj u v → ∀ e : Fin {E},
    (if edgeTable u v = e then (1 : ZMod 2) else 0) +
      ∑ x : Fin {N}, incidenceCoeffs (edgeTable u v) x * incidenceEntry e x =
      potentialCoeffs (labelTable u v) e + potentialCoeffs (labelTable v u) e := by decide

theorem fills : rotation.Fills := by
  intro φ hφ
  refine ⟨fun f => potential φ (faceIndex f), ?_⟩
  intro d
  have hc := coefficient_certificate d.fst d.snd d.adj
  have hs := congrArg (fun c : Fin {E} → ZMod 2 => ∑ e : Fin {E}, c e * φ (indexedEdge e))
    (funext hc)
  simp only [add_mul, Finset.sum_add_distrib,
    Finset.sum_mul] at hs
  have hzero : (∑ e : Fin {E}, ∑ x : Fin {N},
      (incidenceCoeffs (edgeTable d.fst d.snd) x * incidenceEntry e x) *
        φ (indexedEdge e)) = 0 := by
    rw [Finset.sum_comm]
    simp_rw [mul_assoc, ← Finset.mul_sum, ← incidence_coordinates]
    simp [hφ]
  rw [hzero, add_zero] at hs
  simpa [potential, ite_mul, indexedEdge_dart, Dart.symm] using hs

theorem face_length_three (f : rotation.Face) : rotation.faceLength f = 3 := by
  have hp : ∀ u v, graph.Adj u v →
      (fun p : Fin {N} × Fin {N} => (p.2, nextTable p.2 p.1))^[3] (u,v) = (u,v) := by decide
  have hperiod (d : graph.Dart) : rotation.faceNext^[3] d = d := by
    apply Dart.ext
    exact hp _ _ d.adj
  have hfix (d : graph.Dart) : rotation.faceNext d ≠ d := by
    intro he
    exact d.adj.ne (congrArg (fun a : graph.Dart => a.fst) he).symm
  rw [← faceEquiv.left_inv f]
  change rotation.faceLength (rotation.faceOf (representatives (faceIndex f))) = 3
  rw [rotation.face_length_eq_period]
  exact Function.minimalPeriod_eq_prime (hperiod _) (hfix _)

def sphericalMap : SphericalMap {N} where
  graph := graph
  rotation := rotation
  fills := fills

theorem sphericalMap_degree (v : Fin {N}) : sphericalMap.graph.degree v = degTable v := by
  have h := degree_eq v
  rw [← card_neighborSet_eq_degree, ← Nat.card_eq_fintype_card] at h ⊢
  exact h

theorem sphericalMap_triangular (f : sphericalMap.Face) :
    sphericalMap.rotation.faceLength f = 3 := by
  classical
  have h := face_length_three f
  unfold RotationSystem.faceLength at h ⊢
  rw [← Nat.card_eq_fintype_card] at h ⊢
  exact h

theorem sphericalMap_triangulated : sphericalMap.Triangulated :=
  fun _ => sphericalMap_triangular _

end SimpleGraph.{NS}''')
