module

public import Mathlib.Combinatorics.SimpleGraph.PlaneMap.AppearsOcc
public import Mathlib.Combinatorics.SimpleGraph.PlaneMap.C2122MOcc
public import Mathlib.Combinatorics.SimpleGraph.PlaneMap.C2122POcc

/-!
# C2122Appears: an appearance with clean tips is an occurrence

Generated by `gen_appears.py`. In a triangulation with no separating triangle, an appearance
(`Appears`) whose tips share only the centres (`TipsClean`) is an occurrence `C2122M.Occ` or
`C2122P.Occ`, according to the orientation of the face `int 0, int 1, int 2`. The ring vertices
are the rotation successors at the interior vertices, and they are distinct:
* two ring positions seen from one interior vertex are distinct entries of its rotation;
* positions seen from adjacent interior vertices are excluded by `NoSep`, since the triangle is
  facial and the rotations then force equality with a third, distinct entry;
* the two tip-only positions are excluded by `TipsClean`.
-/

@[expose] public section
namespace SimpleGraph.SphericalMap.C2122Appears
open VacancyIcosahedral

variable {n : ℕ}

set_option maxHeartbeats 1000000 in
theorem occ_of_appears {T : SphericalMap n} (htri : T.Triangulated) (hns : NoSep T)
    {int : Fin 4 → Fin n} (A : Appears ![6, 5, 5, 5] T int) (htip : TipsClean T int) :
    (∃ ring, C2122M.Occ T ring int) ∨ (∃ ring, C2122P.Occ T ring int) := by
  rcases hns (int 0) (int 1) (int 2) A.a01 A.a12 A.a02.symm with h0 | h0
  · left
    have f1 : Nx T (int 1) (int 0) (int 2) := h0
    have f2 : Nx T (int 2) (int 1) (int 0) := (nx_tri htri f1).1
    have f3 : Nx T (int 0) (int 2) (int 1) := (nx_tri htri f1).2
    have f4 : Nx T (int 2) (int 0) (int 3) := by
      rcases hns (int 0) (int 2) (int 3) A.a02 A.a23 A.a03.symm with h | h
      · exact h
      · exact absurd (nx_func f3 h) (fun e => absurd (A.int_inj e) (by decide))
    have f5 : Nx T (int 3) (int 2) (int 0) := (nx_tri htri f4).1
    have f6 : Nx T (int 0) (int 3) (int 2) := (nx_tri htri f4).2
    obtain ⟨q2, f7⟩ : ∃ r, Nx T (int 0) (int 1) r := ⟨_, (nx_adj_right f3), rfl⟩
    have f8 : Nx T (int 1) q2 (int 0) := (nx_tri htri f7).2
    obtain ⟨q1, f9⟩ : ∃ r, Nx T (int 0) q2 r := ⟨_, (nx_adj_right f7), rfl⟩
    obtain ⟨q0, f10⟩ : ∃ r, Nx T (int 0) q1 r := ⟨_, (nx_adj_right f9), rfl⟩
    obtain ⟨cl0, ⟨n0_0_1, n0_0_2, n0_0_3, n0_0_4, n0_0_5, n0_1_2, n0_1_3, n0_1_4, n0_1_5, n0_2_3, n0_2_4, n0_2_5, n0_3_4, n0_3_5, n0_4_5⟩⟩ := chain6 (show T.graph.degree (int 0) = 6 by rw [A.deg 0]; rfl) f6 f3 f7 f9 f10
    have f11 : Nx T (int 3) (int 0) q0 := (nx_tri htri cl0).1
    obtain ⟨q4, f12⟩ : ∃ r, Nx T (int 1) (int 2) r := ⟨_, (nx_adj_right f1), rfl⟩
    have f13 : Nx T (int 2) q4 (int 1) := (nx_tri htri f12).2
    obtain ⟨q3, f14⟩ : ∃ r, Nx T (int 1) q4 r := ⟨_, (nx_adj_right f12), rfl⟩
    obtain ⟨cl1, ⟨n1_0_1, n1_0_2, n1_0_3, n1_0_4, n1_1_2, n1_1_3, n1_1_4, n1_2_3, n1_2_4, n1_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 1) = 5 by rw [A.deg 1]; rfl) f8 f1 f12 f14
    obtain ⟨q5, f15⟩ : ∃ r, Nx T (int 2) (int 3) r := ⟨_, (nx_adj_right f4), rfl⟩
    have f16 : Nx T (int 3) q5 (int 2) := (nx_tri htri f15).2
    obtain ⟨cl2, ⟨n2_0_1, n2_0_2, n2_0_3, n2_0_4, n2_1_2, n2_1_3, n2_1_4, n2_2_3, n2_2_4, n2_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 2) = 5 by rw [A.deg 2]; rfl) f13 f2 f4 f15
    obtain ⟨q6, f17⟩ : ∃ r, Nx T (int 3) q0 r := ⟨_, (nx_adj_right f11), rfl⟩
    obtain ⟨cl3, ⟨n3_0_1, n3_0_2, n3_0_3, n3_0_4, n3_1_2, n3_1_3, n3_1_4, n3_2_3, n3_2_4, n3_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 3) = 5 by rw [A.deg 3]; rfl) f16 f5 f11 f17
    have dj0_0 : q0 ≠ int 0 := (n3_2_3).symm
    have dj0_1 : q0 ≠ int 1 := (n0_2_5).symm
    have dj0_2 : q0 ≠ int 2 := (n0_1_5).symm
    have dj0_3 : q0 ≠ int 3 := (n0_0_5).symm
    have dj1_0 : q1 ≠ int 0 := (SimpleGraph.Adj.ne (nx_adj_left f10)).symm
    have dj1_1 : q1 ≠ int 1 := (n0_2_4).symm
    have dj1_2 : q1 ≠ int 2 := (n0_1_4).symm
    have dj1_3 : q1 ≠ int 3 := (n0_0_4).symm
    have dj2_0 : q2 ≠ int 0 := n1_0_1
    have dj2_1 : q2 ≠ int 1 := (n0_2_3).symm
    have dj2_2 : q2 ≠ int 2 := (n0_1_3).symm
    have dj2_3 : q2 ≠ int 3 := (n0_0_3).symm
    have dj3_0 : q3 ≠ int 0 := (n1_1_4).symm
    have dj3_1 : q3 ≠ int 1 := (SimpleGraph.Adj.ne (nx_adj_left cl1)).symm
    have dj3_2 : q3 ≠ int 2 := (n1_2_4).symm
    have dj3_3 : q3 ≠ int 3 := fun e => A.n13 (by rw [← e]; exact (nx_adj_left cl1))
    have dj4_0 : q4 ≠ int 0 := (n1_1_3).symm
    have dj4_1 : q4 ≠ int 1 := n2_0_1
    have dj4_2 : q4 ≠ int 2 := (n1_2_3).symm
    have dj4_3 : q4 ≠ int 3 := n2_0_3
    have dj5_0 : q5 ≠ int 0 := (n2_2_4).symm
    have dj5_1 : q5 ≠ int 1 := (n2_1_4).symm
    have dj5_2 : q5 ≠ int 2 := n3_0_1
    have dj5_3 : q5 ≠ int 3 := (n2_3_4).symm
    have dj6_0 : q6 ≠ int 0 := (n3_2_4).symm
    have dj6_1 : q6 ≠ int 1 := fun e => A.n13 (by rw [← e]; exact (nx_adj_left cl3).symm)
    have dj6_2 : q6 ≠ int 2 := (n3_1_4).symm
    have dj6_3 : q6 ≠ int 3 := (SimpleGraph.Adj.ne (nx_adj_left cl3)).symm
    have rg0_1 : q0 ≠ q1 := (n0_4_5).symm
    have rg0_2 : q0 ≠ q2 := (n0_3_5).symm
    have rg0_3 : q0 ≠ q3 := by
      intro h
      rcases hns (int 0) (int 1) q0 A.a01 (by rw [h]; exact (nx_adj_left cl1)) (nx_adj_left cl0).symm with h1 | h1
      · exact n1_2_4 ((nx_func f1 h1).trans h)
      · exact n0_3_5 (nx_func f7 h1)
    have rg0_4 : q0 ≠ q4 := by
      intro h
      rcases hns (int 0) (int 1) q0 A.a01 (by rw [h]; exact (nx_adj_left f14)) (nx_adj_left cl0).symm with h1 | h1
      · exact n1_2_3 ((nx_func f1 h1).trans h)
      · exact n0_3_5 (nx_func f7 h1)
    have rg0_5 : q0 ≠ q5 := (n3_0_3).symm
    have rg0_6 : q0 ≠ q6 := n3_3_4
    have rg1_2 : q1 ≠ q2 := (n0_3_4).symm
    have rg1_3 : q1 ≠ q3 := by
      intro h
      rcases hns (int 0) (int 1) q1 A.a01 (by rw [h]; exact (nx_adj_left cl1)) (nx_adj_left f10).symm with h1 | h1
      · exact n1_2_4 ((nx_func f1 h1).trans h)
      · exact n0_3_4 (nx_func f7 h1)
    have rg1_4 : q1 ≠ q4 := by
      intro h
      rcases hns (int 0) (int 1) q1 A.a01 (by rw [h]; exact (nx_adj_left f14)) (nx_adj_left f10).symm with h1 | h1
      · exact n1_2_3 ((nx_func f1 h1).trans h)
      · exact n0_3_4 (nx_func f7 h1)
    have rg1_5 : q1 ≠ q5 := by
      intro h
      rcases hns (int 0) (int 2) q1 A.a02 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left f10).symm with h1 | h1
      · exact n2_3_4 ((nx_func f4 h1).trans h)
      · exact n0_2_4 (nx_func f3 h1)
    have rg1_6 : q1 ≠ q6 := by
      intro h
      rcases hns (int 0) (int 3) q1 A.a03 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left f10).symm with h1 | h1
      · exact n3_3_4 ((nx_func f11 h1).trans h)
      · exact n0_1_4 (nx_func f6 h1)
    have rg2_3 : q2 ≠ q3 := n1_0_4
    have rg2_4 : q2 ≠ q4 := n1_0_3
    have rg2_5 : q2 ≠ q5 := by
      intro h
      rcases hns (int 0) (int 2) q2 A.a02 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left f9).symm with h1 | h1
      · exact n2_3_4 ((nx_func f4 h1).trans h)
      · exact n0_2_3 (nx_func f3 h1)
    have rg2_6 : q2 ≠ q6 := by
      intro h
      rcases hns (int 0) (int 3) q2 A.a03 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left f9).symm with h1 | h1
      · exact n3_3_4 ((nx_func f11 h1).trans h)
      · exact n0_1_3 (nx_func f6 h1)
    have rg3_4 : q3 ≠ q4 := (n1_3_4).symm
    have rg3_5 : q3 ≠ q5 := by
      intro h
      rcases hns (int 1) (int 2) q3 A.a12 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left cl1).symm with h1 | h1
      · exact n2_2_4 ((nx_func f2 h1).trans h)
      · exact n1_3_4 (nx_func f12 h1)
    have rg3_6 : q3 ≠ q6 := by
      intro h
      rcases htip q3 (nx_adj_left cl1) (by rw [h]; exact (nx_adj_left cl3)) with e | e
      · exact dj3_0 e
      · exact dj3_2 e
    have rg4_5 : q4 ≠ q5 := n2_0_4
    have rg4_6 : q4 ≠ q6 := by
      intro h
      rcases hns (int 2) (int 3) q4 A.a23 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left f13).symm with h1 | h1
      · exact n3_2_4 ((nx_func f5 h1).trans h)
      · exact (n2_0_4).symm (nx_func f15 h1)
    have rg5_6 : q5 ≠ q6 := n3_0_4
    refine ⟨![q0, q1, q2, q3, q4, q5, q6], {
      ring_inj := ?_
      int_inj := A.int_inj
      disj := ?_
      deg := A.deg
      r0_0 := f9
      r0_1 := f7
      r0_2 := f3
      r0_3 := f6
      r0_4 := cl0
      r0_5 := f10
      r1_0 := cl1
      r1_1 := f14
      r1_2 := f12
      r1_3 := f1
      r1_4 := f8
      r2_0 := f13
      r2_1 := cl2
      r2_2 := f15
      r2_3 := f4
      r2_4 := f2
      r3_0 := f16
      r3_1 := cl3
      r3_2 := f17
      r3_3 := f11
      r3_4 := f5
      }⟩
    · intro s t h; fin_cases s <;> fin_cases t <;> first | rfl | exact absurd h ‹_› | exact absurd h.symm ‹_›
    · intro t a; fin_cases t <;> fin_cases a <;> assumption
  · right
    have f1 : Nx T (int 0) (int 1) (int 2) := h0
    have f2 : Nx T (int 2) (int 0) (int 1) := (nx_tri htri f1).1
    have f3 : Nx T (int 1) (int 2) (int 0) := (nx_tri htri f1).2
    have f4 : Nx T (int 0) (int 2) (int 3) := by
      rcases hns (int 0) (int 2) (int 3) A.a02 A.a23 A.a03.symm with h | h
      · exact absurd (nx_func f2 h) (fun e => absurd (A.int_inj e) (by decide))
      · exact h
    have f5 : Nx T (int 3) (int 0) (int 2) := (nx_tri htri f4).1
    have f6 : Nx T (int 2) (int 3) (int 0) := (nx_tri htri f4).2
    obtain ⟨q0, f7⟩ : ∃ r, Nx T (int 0) (int 3) r := ⟨_, (nx_adj_right f4), rfl⟩
    have f8 : Nx T (int 3) q0 (int 0) := (nx_tri htri f7).2
    obtain ⟨q1, f9⟩ : ∃ r, Nx T (int 0) q0 r := ⟨_, (nx_adj_right f7), rfl⟩
    obtain ⟨q2, f10⟩ : ∃ r, Nx T (int 0) q1 r := ⟨_, (nx_adj_right f9), rfl⟩
    obtain ⟨cl0, ⟨n0_0_1, n0_0_2, n0_0_3, n0_0_4, n0_0_5, n0_1_2, n0_1_3, n0_1_4, n0_1_5, n0_2_3, n0_2_4, n0_2_5, n0_3_4, n0_3_5, n0_4_5⟩⟩ := chain6 (show T.graph.degree (int 0) = 6 by rw [A.deg 0]; rfl) f1 f4 f7 f9 f10
    have f11 : Nx T (int 1) (int 0) q2 := (nx_tri htri cl0).1
    obtain ⟨q3, f12⟩ : ∃ r, Nx T (int 1) q2 r := ⟨_, (nx_adj_right f11), rfl⟩
    obtain ⟨q4, f13⟩ : ∃ r, Nx T (int 1) q3 r := ⟨_, (nx_adj_right f12), rfl⟩
    obtain ⟨cl1, ⟨n1_0_1, n1_0_2, n1_0_3, n1_0_4, n1_1_2, n1_1_3, n1_1_4, n1_2_3, n1_2_4, n1_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 1) = 5 by rw [A.deg 1]; rfl) f3 f11 f12 f13
    have f14 : Nx T (int 2) (int 1) q4 := (nx_tri htri cl1).1
    obtain ⟨q5, f15⟩ : ∃ r, Nx T (int 2) q4 r := ⟨_, (nx_adj_right f14), rfl⟩
    obtain ⟨cl2, ⟨n2_0_1, n2_0_2, n2_0_3, n2_0_4, n2_1_2, n2_1_3, n2_1_4, n2_2_3, n2_2_4, n2_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 2) = 5 by rw [A.deg 2]; rfl) f6 f2 f14 f15
    have f16 : Nx T (int 3) (int 2) q5 := (nx_tri htri cl2).1
    obtain ⟨q6, f17⟩ : ∃ r, Nx T (int 3) q5 r := ⟨_, (nx_adj_right f16), rfl⟩
    obtain ⟨cl3, ⟨n3_0_1, n3_0_2, n3_0_3, n3_0_4, n3_1_2, n3_1_3, n3_1_4, n3_2_3, n3_2_4, n3_3_4⟩, -⟩ := chain5 (show T.graph.degree (int 3) = 5 by rw [A.deg 3]; rfl) f8 f5 f16 f17
    have dj0_0 : q0 ≠ int 0 := n3_0_1
    have dj0_1 : q0 ≠ int 1 := (n0_0_3).symm
    have dj0_2 : q0 ≠ int 2 := (n0_1_3).symm
    have dj0_3 : q0 ≠ int 3 := (n0_2_3).symm
    have dj1_0 : q1 ≠ int 0 := (SimpleGraph.Adj.ne (nx_adj_left f10)).symm
    have dj1_1 : q1 ≠ int 1 := (n0_0_4).symm
    have dj1_2 : q1 ≠ int 2 := (n0_1_4).symm
    have dj1_3 : q1 ≠ int 3 := (n0_2_4).symm
    have dj2_0 : q2 ≠ int 0 := (n1_1_2).symm
    have dj2_1 : q2 ≠ int 1 := (n0_0_5).symm
    have dj2_2 : q2 ≠ int 2 := (n0_1_5).symm
    have dj2_3 : q2 ≠ int 3 := (n0_2_5).symm
    have dj3_0 : q3 ≠ int 0 := (n1_1_3).symm
    have dj3_1 : q3 ≠ int 1 := (SimpleGraph.Adj.ne (nx_adj_left f13)).symm
    have dj3_2 : q3 ≠ int 2 := (n1_0_3).symm
    have dj3_3 : q3 ≠ int 3 := fun e => A.n13 (by rw [← e]; exact (nx_adj_left f13))
    have dj4_0 : q4 ≠ int 0 := (n1_1_4).symm
    have dj4_1 : q4 ≠ int 1 := (n2_2_3).symm
    have dj4_2 : q4 ≠ int 2 := (n1_0_4).symm
    have dj4_3 : q4 ≠ int 3 := (n2_0_3).symm
    have dj5_0 : q5 ≠ int 0 := (n2_1_4).symm
    have dj5_1 : q5 ≠ int 1 := (n2_2_4).symm
    have dj5_2 : q5 ≠ int 2 := (n3_2_3).symm
    have dj5_3 : q5 ≠ int 3 := (n2_0_4).symm
    have dj6_0 : q6 ≠ int 0 := (n3_1_4).symm
    have dj6_1 : q6 ≠ int 1 := fun e => A.n13 (by rw [← e]; exact (nx_adj_left cl3).symm)
    have dj6_2 : q6 ≠ int 2 := (n3_2_4).symm
    have dj6_3 : q6 ≠ int 3 := (SimpleGraph.Adj.ne (nx_adj_left cl3)).symm
    have rg0_1 : q0 ≠ q1 := n0_3_4
    have rg0_2 : q0 ≠ q2 := n0_3_5
    have rg0_3 : q0 ≠ q3 := by
      intro h
      rcases hns (int 0) (int 1) q0 A.a01 (by rw [h]; exact (nx_adj_left f13)) (nx_adj_left f9).symm with h1 | h1
      · exact n1_2_3 ((nx_func f11 h1).trans h)
      · exact n0_1_3 (nx_func f1 h1)
    have rg0_4 : q0 ≠ q4 := by
      intro h
      rcases hns (int 0) (int 1) q0 A.a01 (by rw [h]; exact (nx_adj_left cl1)) (nx_adj_left f9).symm with h1 | h1
      · exact n1_2_4 ((nx_func f11 h1).trans h)
      · exact n0_1_3 (nx_func f1 h1)
    have rg0_5 : q0 ≠ q5 := n3_0_3
    have rg0_6 : q0 ≠ q6 := n3_0_4
    have rg1_2 : q1 ≠ q2 := n0_4_5
    have rg1_3 : q1 ≠ q3 := by
      intro h
      rcases hns (int 0) (int 1) q1 A.a01 (by rw [h]; exact (nx_adj_left f13)) (nx_adj_left f10).symm with h1 | h1
      · exact n1_2_3 ((nx_func f11 h1).trans h)
      · exact n0_1_4 (nx_func f1 h1)
    have rg1_4 : q1 ≠ q4 := by
      intro h
      rcases hns (int 0) (int 1) q1 A.a01 (by rw [h]; exact (nx_adj_left cl1)) (nx_adj_left f10).symm with h1 | h1
      · exact n1_2_4 ((nx_func f11 h1).trans h)
      · exact n0_1_4 (nx_func f1 h1)
    have rg1_5 : q1 ≠ q5 := by
      intro h
      rcases hns (int 0) (int 2) q1 A.a02 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left f10).symm with h1 | h1
      · exact n2_2_4 ((nx_func f2 h1).trans h)
      · exact n0_2_4 (nx_func f4 h1)
    have rg1_6 : q1 ≠ q6 := by
      intro h
      rcases hns (int 0) (int 3) q1 A.a03 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left f10).symm with h1 | h1
      · exact n3_2_4 ((nx_func f5 h1).trans h)
      · exact n0_3_4 (nx_func f7 h1)
    have rg2_3 : q2 ≠ q3 := n1_2_3
    have rg2_4 : q2 ≠ q4 := n1_2_4
    have rg2_5 : q2 ≠ q5 := by
      intro h
      rcases hns (int 0) (int 2) q2 A.a02 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left cl0).symm with h1 | h1
      · exact n2_2_4 ((nx_func f2 h1).trans h)
      · exact n0_2_5 (nx_func f4 h1)
    have rg2_6 : q2 ≠ q6 := by
      intro h
      rcases hns (int 0) (int 3) q2 A.a03 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left cl0).symm with h1 | h1
      · exact n3_2_4 ((nx_func f5 h1).trans h)
      · exact n0_3_5 (nx_func f7 h1)
    have rg3_4 : q3 ≠ q4 := n1_3_4
    have rg3_5 : q3 ≠ q5 := by
      intro h
      rcases hns (int 1) (int 2) q3 A.a12 (by rw [h]; exact (nx_adj_left cl2)) (nx_adj_left f13).symm with h1 | h1
      · exact n2_3_4 ((nx_func f14 h1).trans h)
      · exact n1_1_3 (nx_func f3 h1)
    have rg3_6 : q3 ≠ q6 := by
      intro h
      rcases htip q3 (nx_adj_left f13) (by rw [h]; exact (nx_adj_left cl3)) with e | e
      · exact dj3_0 e
      · exact dj3_2 e
    have rg4_5 : q4 ≠ q5 := n2_3_4
    have rg4_6 : q4 ≠ q6 := by
      intro h
      rcases hns (int 2) (int 3) q4 A.a23 (by rw [h]; exact (nx_adj_left cl3)) (nx_adj_left f15).symm with h1 | h1
      · exact n3_3_4 ((nx_func f16 h1).trans h)
      · exact n1_1_4 (nx_func f6 h1)
    have rg5_6 : q5 ≠ q6 := n3_3_4
    refine ⟨![q0, q1, q2, q3, q4, q5, q6], {
      ring_inj := ?_
      int_inj := A.int_inj
      disj := ?_
      deg := A.deg
      r0_0 := f10
      r0_1 := cl0
      r0_2 := f1
      r0_3 := f4
      r0_4 := f7
      r0_5 := f9
      r1_0 := f12
      r1_1 := f13
      r1_2 := cl1
      r1_3 := f3
      r1_4 := f11
      r2_0 := f14
      r2_1 := f15
      r2_2 := cl2
      r2_3 := f6
      r2_4 := f2
      r3_0 := f16
      r3_1 := f17
      r3_2 := cl3
      r3_3 := f8
      r3_4 := f5
      }⟩
    · intro s t h; fin_cases s <;> fin_cases t <;> first | rfl | exact absurd h ‹_› | exact absurd h.symm ‹_›
    · intro t a; fin_cases t <;> fin_cases a <;> assumption

end SimpleGraph.SphericalMap.C2122Appears
