#!/usr/bin/env python3
"""[Track B] Parse the four generated Lean Occ structures (DiamondP/M, C2122P/M) and emit occ_sched.h:
a straight-line propagation schedule from the seed (int 0, int 1) plus the full list of Nx facts to verify.
Labels: int a -> a (0..3), ring t -> 4 + t.  Nx T x y z  is read as "z follows y in the rotation at x"
(the same reading as StudioMathReview-scripts/occ_search.py).  Because both orientations P and M are checked,
the choice of rotation direction of the input embedding does not matter.
Usage: python3 gen_schedule.py <PlaneMap dir> > occ_sched.h"""
import re, sys
P = sys.argv[1].rstrip('/') + '/'
def parse(t):
    m = re.match(r'(ring|int) (\d+)', t.strip('() ')); k, i = m.group(1), int(m.group(2))
    return i if k == 'int' else 4 + i
out = []
names = ['DiamondP', 'DiamondM', 'C2122P', 'C2122M']
for ns in names:
    occ = open(P + ns + 'Occ.lean').read().split('structure Occ')[1].split('\ntheorem')[0]
    facts = [tuple(parse(x) for x in re.findall(r'\((?:ring|int) \d+\)', l)) for l in occ.splitlines() if ': Nx T' in l]
    degs = [int(x) for x in re.search(r'!\[([\d, ]+)\]', occ.split('deg :')[1]).group(1).split(',')]
    R = max(max(f) for f in facts) - 3; L = 4 + R
    known = {0, 1}; steps = []  # (type, x, a, b): type 0: b = nxt[x][a]; type 1: a = prv[x][b] -> stored as (1,x,b,a)
    ch = True
    while ch:
        ch = False
        for (x, y, z) in facts:
            if x in known and y in known and z not in known: steps.append((0, x, y, z)); known.add(z); ch = True
            elif x in known and z in known and y not in known: steps.append((1, x, z, y)); known.add(y); ch = True
    assert len(known) == L, (ns, known)
    out.append((ns, degs, R, L, steps, facts))
print('/* generated by gen_schedule.py from the Lean Occ structures; do not edit */')
print('#define NCONF %d' % len(out))
for ns, degs, R, L, steps, facts in out:
    print('static const int %s_deg[4] = {%s};' % (ns, ','.join(map(str, degs))))
    print('static const int %s_steps[][4] = {%s};' % (ns, ','.join('{%d,%d,%d,%d}' % s for s in steps)))
    print('static const int %s_facts[][3] = {%s};' % (ns, ','.join('{%d,%d,%d}' % f for f in facts)))
print('typedef struct { const char *name; const int *deg; int R, L, nsteps, nfacts; const int (*steps)[4]; const int (*facts)[3]; } conf_t;')
print('static const conf_t CONFS[NCONF] = {')
for ns, degs, R, L, steps, facts in out:
    print('  {"%s", %s_deg, %d, %d, %d, %d, %s_steps, %s_facts},' % (ns, ns, R, L, len(steps), len(facts), ns, ns))
print('};')
