/* generated by gen_schedule.py from the Lean Occ structures; do not edit */
#define NCONF 4
static const int DiamondP_deg[4] = {5,5,5,5};
static const int DiamondP_steps[][4] = {{1,0,1,5},{0,0,1,2},{0,0,2,3},{0,0,3,4},{0,1,5,6},{0,1,6,7},{0,2,7,8},{0,3,8,9}};
static const int DiamondP_facts[][3] = {{0,5,1},{0,1,2},{0,2,3},{0,3,4},{0,4,5},{1,5,6},{1,6,7},{1,7,2},{1,2,0},{1,0,5},{2,1,7},{2,7,8},{2,8,3},{2,3,0},{2,0,1},{3,2,8},{3,8,9},{3,9,4},{3,4,0},{3,0,2}};
static const int DiamondM_deg[4] = {5,5,5,5};
static const int DiamondM_steps[][4] = {{0,0,1,5},{1,0,1,2},{1,0,2,3},{1,0,3,4},{1,1,5,6},{1,1,6,7},{1,2,7,8},{1,3,8,9}};
static const int DiamondM_facts[][3] = {{0,1,5},{0,2,1},{0,3,2},{0,4,3},{0,5,4},{1,6,5},{1,7,6},{1,2,7},{1,0,2},{1,5,0},{2,7,1},{2,8,7},{2,3,8},{2,0,3},{2,1,0},{3,8,2},{3,9,8},{3,4,9},{3,0,4},{3,2,0}};
static const int C2122P_deg[4] = {6,5,5,5};
static const int C2122P_steps[][4] = {{1,0,1,6},{0,0,1,2},{0,0,2,3},{0,0,3,4},{0,0,4,5},{0,1,6,7},{0,1,7,8},{0,2,8,9},{0,3,9,10}};
static const int C2122P_facts[][3] = {{0,5,6},{0,6,1},{0,1,2},{0,2,3},{0,3,4},{0,4,5},{1,6,7},{1,7,8},{1,8,2},{1,2,0},{1,0,6},{2,1,8},{2,8,9},{2,9,3},{2,3,0},{2,0,1},{3,2,9},{3,9,10},{3,10,4},{3,4,0},{3,0,2}};
static const int C2122M_deg[4] = {6,5,5,5};
static const int C2122M_steps[][4] = {{0,0,1,6},{1,0,1,2},{1,0,2,3},{1,0,3,4},{1,0,4,5},{1,1,6,7},{1,1,7,8},{1,2,8,9},{1,3,9,10}};
static const int C2122M_facts[][3] = {{0,6,5},{0,1,6},{0,2,1},{0,3,2},{0,4,3},{0,5,4},{1,7,6},{1,8,7},{1,2,8},{1,0,2},{1,6,0},{2,8,1},{2,9,8},{2,3,9},{2,0,3},{2,1,0},{3,9,2},{3,10,9},{3,4,10},{3,0,4},{3,2,0}};
typedef struct { const char *name; const int *deg; int R, L, nsteps, nfacts; const int (*steps)[4]; const int (*facts)[3]; } conf_t;
static const conf_t CONFS[NCONF] = {
  {"DiamondP", DiamondP_deg, 6, 10, 8, 20, DiamondP_steps, DiamondP_facts},
  {"DiamondM", DiamondM_deg, 6, 10, 8, 20, DiamondM_steps, DiamondM_facts},
  {"C2122P", C2122P_deg, 7, 11, 9, 21, C2122P_steps, C2122P_facts},
  {"C2122M", C2122M_deg, 7, 11, 9, 21, C2122M_steps, C2122M_facts},
};
