# Builds docs/66666/layout.js: hole-centred vertex positions for the map (site drawing convention, docs/shared/kempe-draw.js).
# Reads docs/66666/data.js (unchanged) and uses docs/shared/hole_layout.py.   Run:  python3 docs/66666/build_layout.py
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'shared'))
from hole_layout import layout, load_data_js, write_layout_js

_, D = load_data_js(os.path.join(HERE, 'data.js'))
out = {}
pos, link, _ = layout(D['rot'], D['hole']); out = {'pos': pos, 'link': link}
write_layout_js(os.path.join(HERE, 'layout.js'), 'SIXRING_LAYOUT', out, 'Generated by docs/66666/build_layout.py from data.js. Do not edit.')
print('wrote', os.path.join(HERE, 'layout.js'))
