#!/bin/sh
# worker 2: fresh random surfaces (generated by rv_gen.py), then engine
cd "$(dirname "$0")"
python3 -I rv_gen.py sphere 3000 20 40 5 101 > out/fresh_sphere5.txt
python3 -I rv_gen.py sphere 4000 12 40 3 202 > out/fresh_sphere3.txt
python3 -I rv_gen.py rp2 3000 10 34 3 303 > out/fresh_rp2_3.txt
python3 -I rv_gen.py rp2 1500 18 36 5 404 > out/fresh_rp2_5.txt
nice -n 10 ./rv_eng -E 2 -s 11 -M 4000000 < out/fresh_sphere5.txt > out/w2_sphere5.log 2> out/w2_sphere5.err
nice -n 10 ./rv_eng -E 2 -s 11 -M 4000000 < out/fresh_sphere3.txt > out/w2_sphere3.log 2> out/w2_sphere3.err
nice -n 10 ./rv_eng -E 1 -s 11 -M 4000000 < out/fresh_rp2_3.txt > out/w2_rp2_3.log 2> out/w2_rp2_3.err
nice -n 10 ./rv_eng -E 1 -s 11 -M 4000000 < out/fresh_rp2_5.txt > out/w2_rp2_5.log 2> out/w2_rp2_5.err
