# Builds docs/cages/layout.js: hole-centred vertex positions for the map (site drawing convention, docs/shared/kempe-draw.js).
# Reads docs/cages/data.js (unchanged) and uses docs/shared/hole_layout.py.   Run:  python3 docs/cages/build_layout.py
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'shared'))
from hole_layout import layout, load_data_js, write_layout_js

_, D = load_data_js(os.path.join(HERE, 'data.js'))
out = {}
out = {'cages': [], 'fcycle': None}
for G in D['cages']:
    hs = []
    for H in G['holes']:
        print(G['name'], H['hole']); pos, link, _ = layout(G['rot'], H['hole']); hs.append({'pos': pos, 'link': link})
    out['cages'].append(hs)
F = D['fcycle']; print('fcycle'); pos, link, _ = layout(F['rot'], F['hole']); out['fcycle'] = {'pos': pos, 'link': link}
write_layout_js(os.path.join(HERE, 'layout.js'), 'CAGES_LAYOUT', out, 'Generated by docs/cages/build_layout.py from data.js. Do not edit.')
print('wrote', os.path.join(HERE, 'layout.js'))
